# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/microservice
spring.datasource.username=postgres
spring.datasource.password=Diplo6838

# JDBC Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration (Optional, but commonly used with Spring Data JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect